---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=100]
      - id: check-merge-conflict
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args:
          [
            "-x",
            "-a",
            "-o",
            "all",
            "-e",
            "SC2292",
            "-e",
            "SC2310",
            "-e",
            "SC2311",
          ]
        files: \.sh$
